-- CREATES A NEW DATATBASE:
CREATE DATABASE IF NOT EXISTS quotes_db;

-- USING THE DATABASE WE CREATED
USE quotes_db;

-- IF THIS TABLE EXISTS - DROP IT BEFORE WE CREATE  - FRESH START:
DROP TABLE IF EXISTS quotes;

-- CREATING A TABLE:
-- THESE ARE THE COLUMN NAMES FOR THE TABLE.  THIS IS TAILORED TO THE NEEDS OF YOUR PROJECT.  FOR A QUOTES DB:
CREATE TABLE IF NOT EXISTS quotes(
     id INT UNSIGNED NOT NULL AUTO_INCREMENT,
     author_first_name VARCHAR(100),
     author_last_name  VARCHAR(100),
     quote TEXT NOT NULL,
     PRIMARY KEY (id)
);

-- IN THE FUTURE - SHOULD BE ABLE TO RUN A COMMAND LIKE THIS SO WE DON'T HAVE TO DO IT MANUALLY EVERY TIME.
-- TO SET UP THE ABOVE:
--      OPEN MYSQL IN THE TERMINAL.
--          -COPY AND PASTE LINES.